version: '3'
services:
  fucked-pirate-backend:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: fucked-pirate-backend
    volumes:
      - ./app:/app
    ports:
      - "80:80"
